[package]
name = "ror2randomitem"
version = "1.0.0"
authors = ["pringledman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
colored = "2.0.0"