[package]
name = "ror2randomitem"
version = "0.1.0"
authors = ["$pence <saplace100@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
colored = "2.0.0"